### ISSUE TITLE
how to  add asm file in makefile 

### ISSUE THREAD

**Issue by xinshuwei** [Analog-Devices-MSDK/VSCode-Maxim#13]
** Visual Studio Code version**
- 1.69.2

** C/C++ Extension version**
1.11.4

** Target microcontroller and evaluation platform**
MAX78000EVKIT

**Describe the bug**
  how to add asm file(.s asm file) in gcc project (edit makefile ?)

**Comment by Jake-Carter** [comment]
Use the `SRCS` variable just like C files, but you must use a capital `.S` file extension.
* `SRCS += myfile.S`

If you need to add any assembly flags to the build you can use the `PROJ_AFLAGS` variable, which is currently undocumented.

See [Build Configuration](https://github.com/Analog-Devices-MSDK/VSCode-Maxim/tree/develop#build-configuration) for more details, and let me know if there's anything I can help clarify.  I'll get some documentation added on the asm files - no one has needed it yet.

**Comment by xinshuwei** [comment]
Thanks replay
![image](https://user-images.githubusercontent.com/27468495/197223125-1b8612fa-cc30-4b8e-b6b2-5c1f6eb9c3f2.png)
I have add .s file ,but have a lots of error

can you help me，thanks

**Comment by xinshuwei** [comment]
![image](https://user-images.githubusercontent.com/27468495/197225362-f82648be-b346-464c-a28d-f28d64b081e8.png)
asm code

**Comment by xinshuwei** [comment]
Thank you, i got it
