### ISSUE TITLE
Flashing error to MAX32760 EvKit_V1

### ISSUE THREAD

**Issue by tk2themax** [Analog-Devices-MSDK/VSCode-Maxim#14]
Following the steps in UG to setup VSCode-Maxim yields error free build, yet flashing results in "Remote communication error.  Target disconnected.: No error."

Full terminal response:
*  Executing task: arm-none-eabi-gdb --cd="C:\Users\TKirkman\VSCODE_Workspace\TK_Project" --se="build/TK_Project.elf" --symbols=build/TK_Project.elf -x="C:\Users\TKirkman\VSCODE_Workspace\TK_Project/.vscode/flash.gdb" --ex="flash_m4 C:/MaximSDK/Tools/OpenOCD cmsis-dap.cfg MAX32670.cfg" --batch 

C:\MaximSDK\Tools\GNUTools\10.3\bin\arm-none-eabi-gdb.exe: warning: Couldn't determine a path for 
the index cache directory.
The target architecture is set to "armv7e-m".
Open On-Chip Debugger 0.11.0+dev-g2de3186d7 (2022-06-17-06:37)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Remote communication error.  Target disconnected.: No error.  

 *  The terminal process "C:\WINDOWS\System32\cmd.exe /d /c arm-none-eabi-gdb --cd="C:\Users\TKirkman\VSCODE_Workspace\TK_Project" --se="build/TK_Project.elf" --symbols=build/TK_Project.elf -x="C:\Users\TKirkman\VSCODE_Workspace\TK_Project/.vscode/flash.gdb" --ex="flash_m4 C:/MaximSDK/Tools/OpenOCD cmsis-dap.cfg MAX32670.cfg" --batch" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by Jake-Carter** [comment]
Hi @tk2themax

What OS are you using?

This error is the most generic message that OpenOCD will throw when the microcontroller is powered off, debugger port is disconnected, etc.  The MAX32670EVKIT has an integrated debugger that should eliminate most of these issues as long as it's plugged in and accessible from the OS.  Does a "DAPLINK" drive present itself when you plug the board in to your PC?

There should be a `flash.log` file in your project with some more detailed OpenOCD logging about the failure.  Can you attach it to this ticket as well?

**Comment by tk2themax** [comment]
Hi

WIN10.  Problem resolved - tried all this on another PC and it was same.  So - thanks for your comments - this led to me to further question the HW itself and there was a switch that had been moved during tramsport.  Schoolboy error.

**Comment by Jake-Carter** [comment]
No problem, glad to hear it's working now
