### ISSUE TITLE
CMSIS Instructions Linker Issue

### ISSUE THREAD

**Issue by jpmur** [Analog-Devices-MSDK/VSCode-Maxim#15]
c:/maximsdk/tools/gnutools/10.3/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld.exe: undefined reference to `__REV` ,
 `__enable_irq` and  `__disable_irq`

Hi, I'm getting this linker error when compiling my code for `MAX32520`.
The error is an undefined reference to the intrinsic ARM functions for enabling/disabling interrupts, as well as the 'REV' function for reversing byte order.
These functions are part of the CMSIS library:
CMSIS\Include\core_cmFunc.h -> __enable_irq / __disable_irq
CMSIS\Include\core_cmInstr.h -> __REV

I can see that these files are being compiled in the system_max32520.d file.

I have tried changing the linker flags (LDFLAGS) in the Makefile according to this: https://stackoverflow.com/questions/19419782/exit-c-text0x18-undefined-reference-to-exit-when-using-arm-none-eabi-gcc
but it didn't fix the issue.
![linker_issue](https://user-images.githubusercontent.com/54812204/211304511-6e739538-b84b-451a-bf47-b484a8215f1e.JPG)

Would appreciate some help fixing this!

**Comment by Jake-Carter** [comment]
Hi @jpmur,

I suspect `adi_mac.c` is missing some header files.  Try adding [mxc_device.h](https://github.com/Analog-Devices-MSDK/msdk/blob/main/Libraries/PeriphDrivers/Include/MAX32520/mxc_device.h).

```C
#include "mxc_device.h"
```

`mxc_device.h` is essentially a wrapper around the [`max32520.h` file](https://github.com/Analog-Devices-MSDK/msdk/blob/main/Libraries/CMSIS/Device/Maxim/MAX32520/Include/max32520.h), which sets up the inclusion of the CMSIS intrinsics and system header properly (see [here](https://github.com/Analog-Devices-MSDK/msdk/blob/273834a57a4db2168d57d61ef825f16ec2c2b9e9/Libraries/CMSIS/Device/Maxim/MAX32520/Include/max32520.h#L194)).

If this still doesn't resolve the issue please zip up your project and attach it to the ticket.  I'd be happy to take a deeper look.

**Comment by jpmur** [comment]
Hi @Jake-Carter 

Issue fixed. I added the mxc_device.h header to a common header file (included in mac.c and others) and it rectified the issue.

Thank you,
Jason
